version: 2

builds:
  - id: trafficmon
    dir: cmd/trafficmon
    main: .
    binary: trafficmon
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
  - id: trafficmon-windows
    dir: cmd/trafficmon
    main: .
    binary: trafficmon
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: trafficmon
    ids: [trafficmon, trafficmon-windows]
    formats: [binary]
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: checksums.txt

release:
  disable: true
