// Package metadata holds the receiver's identity and the metric/attribute
// names it emits, hand written rather than generated by mdatagen since this
// isn't a contrib PR.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

// Type is this receiver's component type, used in a collector config's
// "receivers:" section (e.g. "trafficmon:").
var Type = component.MustNewType("trafficmon")

const (
	// MetricsStability is Development: this receiver's config shape and
	// emitted metric schema are still free to change.
	MetricsStability = component.StabilityLevelDevelopment
	// LogsStability is Development: this receiver's config shape and
	// emitted log schema are still free to change.
	LogsStability = component.StabilityLevelDevelopment
)

// ScopeName identifies the instrumentation scope on every metric/log record
// this receiver emits.
const ScopeName = "github.com/boyvinall/trafficmon/receiver"

// Metric names. All three are namespaced trafficmon.* since none of them
// are standard semconv metrics.
const (
	// MetricNetworkIO is a cumulative monotonic sum of bytes transferred,
	// split by direction via the AttrNetworkIODirection attribute.
	MetricNetworkIO = "trafficmon.network.io"
	// MetricDNSQueryCount is a cumulative monotonic sum of DNS queries
	// observed, per (dns.question.name, dns.question.type).
	MetricDNSQueryCount = "trafficmon.dns.query.count"
	// MetricNetworkSYNCount is a cumulative monotonic sum of outbound TCP
	// SYNs (connection attempts) observed, per remote endpoint.
	MetricNetworkSYNCount = "trafficmon.network.syn.count"
)

// Attribute keys with no equivalent in go.opentelemetry.io/otel/semconv.
const (
	// AttrNetworkIODirection distinguishes MetricNetworkIO's two data
	// points per connection: AttrDirectionTransmit or AttrDirectionReceive.
	AttrNetworkIODirection = "network.io.direction"
	// AttrNetworkInterfaceName names the capture interface a flow, SYN
	// attempt, or DNS query was observed on.
	AttrNetworkInterfaceName = "network.interface.name"
	// AttrDNSQuestionType is the DNS question's record type (e.g. "A",
	// "AAAA").
	AttrDNSQuestionType = "dns.question.type"
	// AttrPeerOverflow marks a data point folded into the cardinality-cap
	// overflow bucket: its remote address/port attributes are omitted in
	// favor of this one.
	AttrPeerOverflow = "network.peer.address.overflow"
	// AttrSYNAttemptCount is the number of SYNs seen for the log record's
	// exact (local, remote) 4-tuple within the trailing synAttemptWindow.
	AttrSYNAttemptCount = "network.syn.attempt_count"
)

// Values for AttrNetworkIODirection.
const (
	AttrDirectionTransmit = "transmit"
	AttrDirectionReceive  = "receive"
)
